"""new-utm-field

Revision ID: 2c7ad303e8fa
Revises: bef9d1e7c356
Create Date: 2024-08-28 19:28:42.399433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7ad303e8fa'
down_revision: Union[str, None] = 'bef9d1e7c356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('utm_data_json', sa.JSON(), nullable=True))
    op.drop_column('tg_user', 'utm_medium')
    op.drop_column('tg_user', 'utm_campaign')
    op.drop_column('tg_user', 'utm_content')
    op.drop_column('tg_user', 'gad_source')
    op.drop_column('tg_user', 'utm_source')
    op.drop_column('tg_user', 'utm_term')
    op.drop_column('tg_user', 'gclid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('gclid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tg_user', sa.Column('utm_term', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tg_user', sa.Column('utm_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tg_user', sa.Column('gad_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tg_user', sa.Column('utm_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tg_user', sa.Column('utm_campaign', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tg_user', sa.Column('utm_medium', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tg_user', 'utm_data_json')
    # ### end Alembic commands ###
