"""question_audio_json_field

Revision ID: 42304bbd251a
Revises: 2c7ad303e8fa
Create Date: 2024-09-02 16:39:18.317376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42304bbd251a'
down_revision: Union[str, None] = '2c7ad303e8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_audio_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_hash', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('question', sa.Column('question_audio_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'question_audio_json')
    op.drop_table('question_audio_file')
    # ### end Alembic commands ###
