"""empty message

Revision ID: 49c95f28c40f
Revises: fa185fcc746e
Create Date: 2024-06-15 16:32:23.963598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c95f28c40f'
down_revision: Union[str, None] = 'fa185fcc746e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_user_question_id', sa.Integer(), nullable=False),
    sa.Column('first_file_name', sa.String(), nullable=False),
    sa.Column('first_part_questions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('second_part_question', sa.String(), nullable=False),
    sa.Column('third_part_questions', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['tg_user_question_id'], ['tg_user_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_data')
    # ### end Alembic commands ###
