"""question_audio_filename_field_added

Revision ID: 4cde244673b5
Revises: 2c7ad303e8fa
Create Date: 2024-08-30 20:03:31.372823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cde244673b5'
down_revision: Union[str, None] = '2c7ad303e8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_audio_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'question_audio_filename')
    # ### end Alembic commands ###
