"""utm_metrics_changed_tg_user

Revision ID: 5be58f5e7e7f
Revises: 7d2c727e5dc6
Create Date: 2024-08-14 17:55:07.083457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be58f5e7e7f'
down_revision: Union[str, None] = '7d2c727e5dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('utm_source', sa.String(), nullable=True))
    op.add_column('tg_user', sa.Column('utm_medium', sa.String(), nullable=True))
    op.add_column('tg_user', sa.Column('utm_campaign', sa.String(), nullable=True))
    op.add_column('tg_user', sa.Column('utm_content', sa.String(), nullable=True))
    op.drop_column('tg_user', 'adv_channel')
    op.drop_column('tg_user', 'adv_title_utm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('adv_title_utm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tg_user', sa.Column('adv_channel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tg_user', 'utm_content')
    op.drop_column('tg_user', 'utm_campaign')
    op.drop_column('tg_user', 'utm_medium')
    op.drop_column('tg_user', 'utm_source')
    # ### end Alembic commands ###
