"""tg_user_pts

Revision ID: 712f80af7db3
Revises: 2709c65bd722
Create Date: 2024-06-26 20:57:17.181352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712f80af7db3'
down_revision: Union[str, None] = '2709c65bd722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('pts', sa.Integer(), server_default='3', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'pts')
    # ### end Alembic commands ###
