"""tg_uq_priority_queue_field

Revision ID: 8724f1de9cc4
Revises: 712f80af7db3
Create Date: 2024-07-01 13:02:51.440945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8724f1de9cc4'
down_revision: Union[str, None] = '712f80af7db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user_question', sa.Column('premium_queue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user_question', 'premium_queue')
    # ### end Alembic commands ###
