"""on_delete=CASCADE

Revision ID: e4c0c28b7a3c
Revises: ff8508c9b10f
Create Date: 2024-08-22 19:20:18.984412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c0c28b7a3c'
down_revision: Union[str, None] = 'ff8508c9b10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('poll_feedback_user_id_fkey', 'poll_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'poll_feedback', 'tg_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('temp_data_tg_user_question_id_fkey', 'temp_data', type_='foreignkey')
    op.create_foreign_key(None, 'temp_data', 'tg_user_question', ['tg_user_question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tg_user_activity_user_id_fkey', 'tg_user_activity', type_='foreignkey')
    op.create_foreign_key(None, 'tg_user_activity', 'tg_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tg_user_pts_user_id_fkey', 'tg_user_pts', type_='foreignkey')
    op.create_foreign_key(None, 'tg_user_pts', 'tg_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tg_user_question_user_id_fkey', 'tg_user_question', type_='foreignkey')
    op.create_foreign_key(None, 'tg_user_question', 'tg_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tg_user_question_metric_uq_id_fkey', 'tg_user_question_metric', type_='foreignkey')
    op.create_foreign_key(None, 'tg_user_question_metric', 'tg_user_question', ['uq_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tg_user_review_user_id_fkey', 'tg_user_review', type_='foreignkey')
    op.create_foreign_key(None, 'tg_user_review', 'tg_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tg_user_status_user_id_fkey', 'tg_user_status', type_='foreignkey')
    op.create_foreign_key(None, 'tg_user_status', 'tg_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tg_user_wallet_user_id_fkey', 'tg_user_wallet', type_='foreignkey')
    op.create_foreign_key(None, 'tg_user_wallet', 'tg_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tg_user_wallet', type_='foreignkey')
    op.create_foreign_key('tg_user_wallet_user_id_fkey', 'tg_user_wallet', 'tg_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'tg_user_status', type_='foreignkey')
    op.create_foreign_key('tg_user_status_user_id_fkey', 'tg_user_status', 'tg_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'tg_user_review', type_='foreignkey')
    op.create_foreign_key('tg_user_review_user_id_fkey', 'tg_user_review', 'tg_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'tg_user_question_metric', type_='foreignkey')
    op.create_foreign_key('tg_user_question_metric_uq_id_fkey', 'tg_user_question_metric', 'tg_user_question', ['uq_id'], ['id'])
    op.drop_constraint(None, 'tg_user_question', type_='foreignkey')
    op.create_foreign_key('tg_user_question_user_id_fkey', 'tg_user_question', 'tg_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'tg_user_pts', type_='foreignkey')
    op.create_foreign_key('tg_user_pts_user_id_fkey', 'tg_user_pts', 'tg_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'tg_user_activity', type_='foreignkey')
    op.create_foreign_key('tg_user_activity_user_id_fkey', 'tg_user_activity', 'tg_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'temp_data', type_='foreignkey')
    op.create_foreign_key('temp_data_tg_user_question_id_fkey', 'temp_data', 'tg_user_question', ['tg_user_question_id'], ['id'])
    op.drop_constraint(None, 'poll_feedback', type_='foreignkey')
    op.create_foreign_key('poll_feedback_user_id_fkey', 'poll_feedback', 'tg_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
