"""additional_utm_metrics

Revision ID: e7250acb6b7c
Revises: e4c0c28b7a3c
Create Date: 2024-08-23 01:18:31.417254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7250acb6b7c'
down_revision: Union[str, None] = 'e4c0c28b7a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('utm_term', sa.String(), nullable=True))
    op.add_column('tg_user', sa.Column('gad_source', sa.String(), nullable=True))
    op.add_column('tg_user', sa.Column('gclid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'gclid')
    op.drop_column('tg_user', 'gad_source')
    op.drop_column('tg_user', 'utm_term')
    # ### end Alembic commands ###
