"""user_referrer

Revision ID: ecaac7959be3
Revises: 8724f1de9cc4
Create Date: 2024-07-01 18:20:30.638723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecaac7959be3'
down_revision: Union[str, None] = '8724f1de9cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('completed_questions', sa.Integer(), server_default='0', nullable=True))
    op.add_column('tg_user', sa.Column('referrer_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tg_user', 'tg_user', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tg_user', type_='foreignkey')
    op.drop_column('tg_user', 'referrer_id')
    op.drop_column('tg_user', 'completed_questions')
    # ### end Alembic commands ###
