"""tg_user_question_metric_table

Revision ID: ef7c6a38eb47
Revises: 68a743fa19e2
Create Date: 2024-08-06 20:42:06.581508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7c6a38eb47'
down_revision: Union[str, None] = '68a743fa19e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_user_question_metric',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uq_id', sa.BigInteger(), nullable=True),
    sa.Column('metric_id', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uq_id'], ['tg_user_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_user_question_metric')
    # ### end Alembic commands ###
