"""unique_constraint_userquestion

Revision ID: fa185fcc746e
Revises: 8fa9a70960c3
Create Date: 2024-06-13 17:43:56.540153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa185fcc746e'
down_revision: Union[str, None] = '8fa9a70960c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_question', 'tg_user_question', ['user_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_question', 'tg_user_question', type_='unique')
    # ### end Alembic commands ###
