"""metrics_data_table

Revision ID: ff8508c9b10f
Revises: 5be58f5e7e7f
Create Date: 2024-08-22 18:53:00.805187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8508c9b10f'
down_revision: Union[str, None] = '5be58f5e7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_data',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('metrics_string', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics_data')
    # ### end Alembic commands ###
